from pathlib import Path

from app.core.config import settings
from app.models.norm_clause_entry import NormClauseEntry
from app.models.norm_commentary_entry import NormCommentaryEntry
from app.models.project_ai_settings import ProviderApiConfig
from app.models.user import AuthenticatedUser, UserRole
from app.repositories.norm_structure_repository import NormStructureRepository
from app.services.audit_service import AuditService
from app.services.document_service import DocumentService
from app.services.norm_library_service import NormLibraryService
from app.services.ocr_dispatcher import OCRDispatcher
from app.services.project_ai_settings_service import ProjectAiSettingsService
from app.workers.process_norm_document import process_norm_document


class FakeRemoteOCRService:
    def extract(self, *, document_path: Path, config):
        return {
            "provider": "remote-ocr",
            "markdown_text": (
                "# 1 General\n"
                "1.0.1 General clause text for the project.\n\n"
                "## 1.1 Scope\n"
                "1.1.1 Scope clause text that explains the implementation scope.\n"
                "\n"
                "# 修订说明\n"
                "Intro text that should be ignored.\n"
                "## 目次\n"
                "1.1 Scope (11)\n"
                "# 1 General\n"
                "## 1.1 Scope\n"
                "1.1.1 Detailed AI commentary\n"
            ),
            "layout_payload": {
                "pages": [
                    {
                        "page": 1,
                        "text": (
                            "1 General 1.0.1 General clause text for the project. "
                            "1.1 Scope 1.1.1 Scope clause text that explains the "
                            "implementation scope."
                        ),
                    }
                ]
            },
            "metadata": {
                "source_path": str(document_path),
                "provider_model": config.model,
            },
        }


class FakeNormAIStructurer:
    def generate(
        self,
        *,
        document_id: str,
        markdown_text: str,
        page_texts: list[dict],
        baseline_clause_index: dict,
        config,
    ):
        entries = []
        for entry in baseline_clause_index["entries"]:
            enriched = dict(entry)
            if entry["node_type"] == "clause":
                enriched["summary_text"] = f"AI summary for {entry['label']}"
                enriched["tags"] = ["mandatory"] if entry["label"] == "1.1.1" else []
                enriched["commentary_summary"] = (
                    "Detailed AI commentary" if entry["label"] == "1.1.1" else ""
                )
            else:
                enriched["summary_text"] = entry["title"]
                enriched["tags"] = []
            entries.append(enriched)

        return (
            {
                "summary_text": f"AI clause index generated by {config.model}",
                "entries": entries,
                "tree": baseline_clause_index["tree"],
            },
            {
                "summary_text": "AI commentary map",
                "tree": [],
                "entries": [
                    {
                        "document_id": document_id,
                        "label": "1.1.1",
                        "title": "1.1.1",
                        "node_type": "clause",
                        "parent_label": "1.1",
                        "page_start": 1,
                        "page_end": 1,
                        "commentary_text": "Detailed AI commentary",
                        "summary_text": "AI commentary summary",
                        "tags": ["mandatory"],
                    }
                ],
                "commentary_map": {"1.1.1": "Detailed AI commentary"},
                "errors": [],
            },
        )


class InMemoryNormStructureRepository(NormStructureRepository):
    def __init__(self) -> None:
        self.clause_entries: list[NormClauseEntry] = []
        self.commentary_entries: list[NormCommentaryEntry] = []

    def supports_persisted_search(self) -> bool:
        return False

    def reset(self) -> None:
        self.clause_entries = []
        self.commentary_entries = []

    def replace_clause_entries(
        self,
        document_id: str,
        entries: list[NormClauseEntry],
    ) -> None:
        self.clause_entries = [
            entry for entry in self.clause_entries if entry.document_id != document_id
        ] + entries

    def replace_commentary_entries(
        self,
        document_id: str,
        entries: list[NormCommentaryEntry],
    ) -> None:
        self.commentary_entries = [
            entry
            for entry in self.commentary_entries
            if entry.document_id != document_id
        ] + entries

    def list_clause_entries(self, document_id: str) -> list[NormClauseEntry]:
        return [
            entry for entry in self.clause_entries if entry.document_id == document_id
        ]

    def list_commentary_entries(
        self,
        document_id: str,
    ) -> list[NormCommentaryEntry]:
        return [
            entry
            for entry in self.commentary_entries
            if entry.document_id == document_id
        ]

    def search_clause_results(self, **kwargs):
        return None


def test_process_norm_document_uses_saved_project_ocr_and_ai_settings(
    tmp_path: Path,
    monkeypatch,
):
    monkeypatch.setattr(settings, "storage_root", tmp_path / "storage-root")
    documents = DocumentService(
        state_path=tmp_path / "documents.json",
        storage_root=tmp_path / "storage-root",
    )
    audit = AuditService(state_path=tmp_path / "audit.json")
    dispatcher = OCRDispatcher(
        audit=audit,
        state_path=tmp_path / "jobs.json",
    )
    settings_service = ProjectAiSettingsService(
        state_path=tmp_path / "project-ai-settings.json",
    )
    structure_repository = InMemoryNormStructureRepository()
    library = NormLibraryService(
        documents=documents,
        structure_repository=structure_repository,
    )
    settings_service.update_settings(
        "project-alpha",
        settings_service.get_settings("project-alpha").model_copy(
            update={
                "ocr": ProviderApiConfig(
                    base_url="https://ocr.example.test/extract",
                    api_key="ocr-secret",
                    model="mineru-remote",
                ),
                "analysis": ProviderApiConfig(
                    base_url="https://ai.example.test/v1",
                    api_key="ai-secret",
                    model="deepseek-chat",
                ),
            }
        ),
    )

    user = AuthenticatedUser(
        id="user-pm",
        organization_id="org-1",
        role=UserRole.PROJECT_MANAGER,
        display_name="Project Manager",
    )
    document, _version, artifact = documents.create_upload(
        current_user=user,
        project_id="project-alpha",
        filename="grid-standard.pdf",
        content_type="application/pdf",
        content=b"%PDF-1.7 sample",
    )

    job, result = process_norm_document(
        document_id=document.id,
        document_path=Path(artifact.storage_path),
        provider_name="mineru",
        dispatcher=dispatcher,
        documents=documents,
        structure_repository=structure_repository,
        ai_settings=settings_service,
        remote_ocr=FakeRemoteOCRService(),
        ai_structurer=FakeNormAIStructurer(),
    )

    audit_steps = [item["step"] for item in audit.list_for_job(job.id)]
    target_clause = next(
        entry for entry in structure_repository.clause_entries if entry.label == "1.1.1"
    )
    target_commentary = next(
        entry
        for entry in structure_repository.commentary_entries
        if entry.label == "1.1.1"
    )

    assert result is not None
    assert job.provider_name == "configured-ocr"
    assert job.status.value == "completed"
    assert documents.get_document(document.id).status == "indexed"
    assert "ai_structure_completed" not in audit_steps
    assert target_clause.summary_text == "Scope clause text that explains the implementation scope."
    assert target_clause.commentary_summary == "Detailed AI commentary"
    assert target_clause.tags == []
    assert target_commentary.commentary_text == "Detailed AI commentary"
    assert target_commentary.tags == []
